import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { Annonse } from './components';
import { phone } from './icons';
import { hammer } from './images';

const inter = Inter({ subsets: ['latin'] });
export default function Home() {
	return (
		<>
			<Head>
				<title>GreenCircle</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div>
					<Annonse
						image={hammer}
						tool="Hammer"
						name="Marrti Harrma"
						location="Trondheim"
						description="bla bla bla bla bla bla bla bla bla bla bla blabla bla bla bla bla blabla bla bla blabla blabla bla bla bla bla blabla bla bla bla bla blabla bla blaaa"
						phoneicon={phone}
					></Annonse>
				</div>
			</main>
		</>
	);
}
