import React from 'react';
import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { Annonsecontainer, Annonseside } from './components';
import { phone } from './icons';
import { hammer } from './images';

export default function Home() {
	const ref = React.useRef(null);
	function annonseClicked(data) {
		ref.current.style.display = 'inherit';
		console.log();
	}
	const myUser = {
		name: 'Marrti Harrma',
		telephone: '48181451',
		email: 'larsengo@stud.ntnu.no',
		rating: '5',
		annonser: []
	};
	const myAnnonse = {
		image: hammer,
		title: 'Hammer',
		name: 'Marrti Harrma',
		location: 'Trondheim',
		description:
			'bla bla bla bla bla bla bla bla bla bla bla blabla bla bla bla bla blabla bla bla blabla blabla bla bla bla bla blabla bla bla bla bla blabla bla blaaa',
		owner: myUser,
		numfavourites: 0,
		phoneicon: phone
	};
	myUser.annonser.push(myAnnonse);
	let annonser = [myAnnonse, myAnnonse, myAnnonse, myAnnonse, myAnnonse, myAnnonse, myAnnonse];
	return (
		<>
			<Head>
				<title>GreenCircle</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div ref={ref} style={{ display: 'none' }}>
					<Annonseside data={myAnnonse}></Annonseside>
				</div>
				<div>
					<Annonsecontainer data={annonser} annonseClicked={annonseClicked}></Annonsecontainer>
				</div>
			</main>
		</>
	);
}
