import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { Annonse, Annonsecontainer, Annonseside } from './components';
import { phone } from './icons';
import { hammer } from './images';

const inter = Inter({ subsets: ['latin'] });
export default function Home() {
	function annonseClicked(data) {
		console.log(data);
	}
	const myUser = {
		name: 'Marrti Harrma',
		telephone: '48181451',
		email: 'larsengo@stud.ntnu.no',
		rating: '5',
		annonser: []
	};
	const myAnnonse = {
		image: hammer,
		title: 'Hammer',
		name: 'Marrti Harrma',
		location: 'Trondheim',
		description:
			'bla bla bla bla bla bla bla bla bla bla bla blabla bla bla bla bla blabla bla bla blabla blabla bla bla bla bla blabla bla bla bla bla blabla bla blaaa',
		phoneicon: phone,
		owner: myUser
	};
	myUser.annonser.push(myAnnonse);
	let annonser = [myAnnonse, myAnnonse, myAnnonse, myAnnonse, myAnnonse, myAnnonse, myAnnonse];
	return (
		<>
			<Head>
				<title>GreenCircle</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Annonseside data={myAnnonse}></Annonseside>
				<div>
					<Annonsecontainer data={annonser} annonseClicked={annonseClicked}></Annonsecontainer>
				</div>
			</main>
		</>
	);
}
